optim: adam
init: xavier_uniform
max_epoch: 100
batch_type: folded
batch_size: 1
accum_grad: 8
num_workers: 2
optim_conf:
    lr: 1.0e-03
    eps: 1.0e-08
    weight_decay: 1.0e-07
patience: 10
val_scheduler_criterion:
- valid
- loss
best_model_criterion:
-   - valid
    - si_snr
    - max
-   - valid
    - loss
    - min
keep_nbest_models: 1
scheduler: reducelronplateau
scheduler_conf:
    mode: min
    factor: 0.5
    patience: 3
model_conf:
    loss_type: si_snr
    expand_informed: true
    mask_before_fusion: true
informed_encoder: embedding
informed_encoder_conf:
    input_size: 71
    output_size: 256
encoder: conv
encoder_conf:
    in_channel: 5
    channel: 256
    kernel_size: 20
    stride: 10
fusion: concat
decoder: conv
decoder_conf:
    channel: 256
    kernel_size: 20
    stride: 10
separator: tcn
separator_conf:
    input_dim: 512
    output_dim: 256
    num_spk: 1
    layer: 8
    stack: 4
    bottleneck_dim: 256
    hidden_dim: 512
    kernel: 3
    causal: False
    norm_type: "gLN"
    nonlinear: relu
    ref_channel: 3
