optim: adam
init: xavier_uniform
max_epoch: 100
batch_type: folded
batch_size: 4
accum_grad: 4
num_workers: 4
optim_conf:
    lr: 1.0e-03
    eps: 1.0e-08
    weight_decay: 1.0e-07
patience: 10
val_scheduler_criterion:
- valid
- loss
best_model_criterion:
-   - valid
    - si_snr
    - max
-   - valid
    - loss
    - min
keep_nbest_models: 1
scheduler: reducelronplateau
scheduler_conf:
    mode: min
    factor: 0.5
    patience: 3
model_conf:
    loss_type: si_snr
    mask_before_fusion: true
informed_encoder: tactron
informed_encoder_conf:
    idim: 71
    embed_dim: 256
    eunits: 256
    econv_chans: 256
encoder: stft
fusion: transformer
fusion_conf:
    input_size: 257
    attention_dim: 256
    attention_heads: 4
    num_blocks: 4
    linear_units: 2048
decoder: stft
separator: tcn
separator_conf:
    input_dim: 256
    output_dim: 257
    num_spk: 1
    layer: 8
    stack: 4
    bottleneck_dim: 256
    hidden_dim: 512
    kernel: 3
    causal: False
    norm_type: "gLN"
    nonlinear: relu
